### ISSUE TITLE
Allow null values in property objects

### ISSUE THREAD

**Issue by raelg** [HalBuilder/halbuilder-json#13]
Hi, 

Currently, null values in objects are not allowed, as JsonRepresentationReader uses Guava's ImmutableMap internally, which does not permit null keys or values. While it may be dubious practice to have a null value (as returning a null value from a Java Map may mean either the key does not exist or it does exist and is null), however, this is still valid JSON, which means it probably should be handled. 

The simplest solution looks to be to remove the ImmutableMap.copyOf wrapper. 

https://github.com/HalBuilder/halbuilder-json/blob/049d3edf2f16c2e327e9773824b10eec93423836/src/main/java/com/theoryinpractise/halbuilder/json/JsonRepresentationReader.java#L134-L136

example failing HAL extract: 

```javascript
  {
    .... 
    "page": {
       "offset": null,
       "limit": null
     },
   ...
 }
```

Thanks.

**Comment by talios** [comment]
This is currently now working under commit 5e2c7527f32a9d, with the switch away from Guava's ImmutableMaps in favour of using Javaslang persistent maps/lists thru out in the eventual 5.x release series.
