### ISSUE TITLE
JsonRepresentationReader converts Number to String

### ISSUE THREAD

**Issue by martinei** [HalBuilder/halbuilder-json#14]
Currenlty JSON Fields of type Number are silently converted to Java Strings.  A more natural choice would be BigDecimal.

**Comment by martinei** [comment]
The Same Problem exists for Boolean: JSON true and false are silently converted to String, silently dropping JSON type information.

**Comment by talios** [comment]
Hi @martinei, this is now fixed in the current HEAD@develop commits, which are now all Java 8 / Javaslang based.  I could backport the change to a hotfix on master and push out a release if you needed it tho...
