### ISSUE TITLE
Inconsistent behavior with _links vs _embedded _links

### ISSUE THREAD

**Issue by keki007** [HalBuilder/halbuilder-json#18]
Hi,

See below, I would expect the _embedded.items.applicants not to be an array.

```
{
  "_links": {
    "self": {
      "href": "https://localhost:8443/applications"
    }
  },
  "_embedded": {
    "items": [
      {
        "_links": {
          "self": {
            "href": "https://localhost:8443/applications/11111111"
          },
          "applicants": [
            {
              "href": "https://localhost:8443/applications/11111111/applicants"
            }
          ]
        }
      }
    ]
  }
}
```

**Comment by talios** [comment]
How are you adding the "applications" set there?  In the 4.x series, if you want a single element array to drop back to a object, you'd add the COALESCE_LINKS flag when rendering.

**Comment by sventorben** [comment]
I think COALESCE_LINKS is not working, because of [this issue](https://github.com/HalBuilder/halbuilder-json/commit/4bb7c06ab1735b85791299a5995560793d040304#commitcomment-17025056).

**Comment by talios** [comment]
4.0.5 released after fixing embedded links and tests.

**Comment by talios** [comment]
My bad - my originally comment should have been for adding COALESCE_ARRAYS, COALESCE_LINKS collapses similar target links to a single space separated rel.  4.0.6 will be released shortly reverting the changes mistakingly added in 4.0.5.

**Comment by talios** [comment]
It may be easier to talk in https://gitter.im/halbuilder/Lobby
